import { getGoldBubble, getMarketPrice, TELEGRAM_BOT_URL } from "@/lib/api";
import GoldCalculator from "@/components/GoldCalculator";
import ProductCatalog from "@/components/ProductCatalog";
import { formatToman } from "@/data/products";

export const dynamic = "force-dynamic";

const forestImage = "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=85";
const jewelryImage = "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1400&q=85";

export default async function Home() {
  const [marketResult, bubbleResult] = await Promise.allSettled([getMarketPrice(), getGoldBubble()]);
  const market = marketResult.status === "fulfilled" ? marketResult.value : null;
  const bubble = bubbleResult.status === "fulfilled" ? bubbleResult.value : null;

  return (
    <main className="overflow-x-hidden bg-[#f5f1e9] text-[#292b26]">
      <div className="border-b border-[#dfe1d7] bg-[#faf8f2]"><div className="waresh-container flex min-h-9 items-center justify-between gap-4 text-[11px] text-[#73776f]"><span>وارش گلد · فروشگاه طلا و جواهر</span><span className="font-bold text-[#6b7c62]">{market ? `طلای ۱۸ عیار ${formatToman(market.gold18Price)}` : "قیمت بازار در حال دریافت…"}</span></div></div>

      <header className="sticky top-0 z-50 border-b border-[#dedfd7]/80 bg-[#faf8f2]/90 backdrop-blur-xl"><div className="waresh-container flex h-[76px] items-center justify-between gap-5">
        <a href="#top" className="shrink-0" aria-label="وارش گلد"><img src="/waresh-gold-logo-green.png" alt="وارش گلد" className="h-12 w-auto object-contain" /></a>
        <nav className="hidden items-center gap-8 text-sm font-semibold text-[#62685e] lg:flex"><a className="waresh-link" href="#products">محصولات</a><a className="waresh-link" href="#gifts">هدیه</a><a className="waresh-link" href="#prices">قیمت امروز</a><a className="waresh-link" href="/tools">ابزار طلا</a><a className="waresh-link" href="/about">درباره وارش</a></nav>
        <div className="flex items-center gap-2"><a href={TELEGRAM_BOT_URL} target="_blank" rel="noopener noreferrer" className="hidden rounded-full bg-[#b28b4c] px-5 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#9d773d] sm:inline-flex">گفتگو در تلگرام</a><a href="#products" className="inline-flex h-11 w-11 items-center justify-center rounded-full border border-[#d8d2c7] bg-white/60 text-lg text-[#3d443b] transition hover:bg-white lg:hidden" aria-label="منوی سایت">☰</a></div>
      </div></header>

      <section id="top" className="relative min-h-[720px] overflow-hidden bg-[#20372c] text-white"><img src={forestImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45" aria-hidden="true" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,39,31,0.98)_0%,rgba(24,52,40,0.80)_42%,rgba(20,42,34,0.35)_100%)]" /><div className="waresh-rain absolute inset-0 opacity-20" aria-hidden="true" />
        <div className="waresh-container relative grid min-h-[720px] items-center gap-14 py-20 lg:grid-cols-[1.1fr_0.9fr]"><div className="max-w-2xl"><p className="text-xs font-bold tracking-[0.24em] text-[#d7bf8b]">WARESH GOLD · JEWELRY</p><h1 className="mt-6 text-5xl font-extrabold leading-[1.35] tracking-tight sm:text-7xl">طلای خاص،<span className="block text-[#d8bd7e]">برای لحظه‌های خاص.</span></h1><p className="mt-7 max-w-xl text-base leading-9 text-[#d9e0da] sm:text-lg">انتخابی از طلا و جواهرات ظریف، کم‌اجرت و ماندگار؛ با قیمت بازار و ابزارهای دقیق وارش گلد.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#products" className="inline-flex items-center justify-center rounded-full bg-[#b28b4c] px-7 py-4 font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#9d773d]">مشاهده محصولات</a><a href="#prices" className="inline-flex items-center justify-center rounded-full border border-white/25 bg-white/10 px-7 py-4 font-bold text-white backdrop-blur-sm transition hover:bg-white/15">قیمت امروز</a></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-xs text-[#c7d0c8]"><span>محصولات منتخب</span><span>قیمت شفاف</span><span>محاسبه دقیق</span></div></div>
          <div className="relative mx-auto w-full max-w-[440px] lg:justify-self-end"><div className="overflow-hidden rounded-[3rem] border border-white/15 bg-white/10 p-2 shadow-[0_40px_100px_rgba(0,0,0,0.3)] backdrop-blur-sm"><div className="relative overflow-hidden rounded-[2.6rem]"><img src={jewelryImage} alt="نمونه‌ای از طلا و جواهرات وارش" className="h-[500px] w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(180deg,transparent_45%,rgba(20,39,31,0.82)_100%)]" /><div className="absolute inset-x-7 bottom-7"><p className="text-[10px] font-bold tracking-[0.22em] text-[#dbc58d]">SELECTED GOLD</p><p className="mt-2 text-2xl font-extrabold">زیبایی، بدون هیاهو.</p></div></div></div></div>
        </div>
      </section>

      <section id="products" className="bg-[#f5f1e9] py-24 sm:py-32"><div className="waresh-container"><div className="mb-12 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold tracking-[0.2em] text-[#a17c45]">THE COLLECTION</p><h2 className="mt-4 text-4xl font-extrabold tracking-tight text-[#292d28] sm:text-5xl">محصولات وارش</h2><p className="mt-4 max-w-xl text-base leading-8 text-[#72766f]">دسته‌بندی کن، بازه قیمت را انتخاب کن و محصول مناسب خودت را پیدا کن.</p></div><a href={TELEGRAM_BOT_URL} target="_blank" rel="noopener noreferrer" className="text-sm font-bold text-[#96713b] transition hover:text-[#73552b]">برای خرید و مشاوره ← تلگرام</a></div><ProductCatalog /></div></section>

      <section id="gifts" className="relative overflow-hidden bg-[#23372d] py-24 text-white sm:py-28"><div className="waresh-container relative"><div className="max-w-2xl"><p className="text-xs font-bold tracking-[0.2em] text-[#d8bd7e]">GIFT EDIT</p><h2 className="mt-5 text-4xl font-extrabold sm:text-5xl">هدیه‌ای که می‌ماند.</h2><p className="mt-5 text-base leading-8 text-[#d6ddd6]">برای انتخاب هدیه، از فیلتر بازه قیمت در مجموعه بالا استفاده کن؛ انتخاب بر اساس بودجه، ساده و شفاف.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{[["۳ تا ۱۰ میلیون","انتخاب‌های ظریف و اقتصادی"],["۱۰ تا ۲۰ میلیون","برای یک هدیه ویژه"],["۲۰ تا ۳۰ میلیون","انتخاب‌های چشمگیرتر"]].map(([range,description])=><a key={range} href="#products" className="group rounded-[2rem] border border-white/10 bg-white/[0.06] p-7 backdrop-blur transition hover:-translate-y-1 hover:bg-white/[0.1]"><span className="text-sm font-bold text-[#dbc58d]">{range}</span><p className="mt-5 text-xl font-extrabold">{description}</p><span className="mt-8 block text-sm text-[#bfc9c0] transition group-hover:text-white">دیدن مجموعه ←</span></a>)}</div></div></section>

      <section id="prices" className="bg-[#e9eee7] py-24 sm:py-28"><div className="waresh-container"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><p className="text-xs font-bold tracking-[0.2em] text-[#9b7843]">MARKET / LIVE</p><h2 className="mt-4 text-4xl font-extrabold text-[#293129] sm:text-5xl">نبض بازار</h2><p className="mt-5 max-w-lg text-base leading-8 text-[#70776e]">قیمت‌های بازار از هسته اصلی وارش دریافت می‌شوند؛ سایت فقط آن‌ها را نمایش می‌دهد و محاسبات را به سرویس مطمئن طلا می‌سپارد.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:max-w-md">{[["طلای ۱۸ عیار",market?formatToman(market.gold18Price):"—"],["دلار تهران",market?formatToman(market.currencyPrice):"—"],["انس جهانی",market?Number(market.ouncePrice).toLocaleString("en-US"):"—"],["حباب",bubble?formatToman(bubble.bubbleAmount):"—"]].map(([label,value])=><div key={label} className="rounded-[1.5rem] bg-[#faf8f2] p-5"><p className="text-xs text-[#858a83]">{label}</p><p className="mt-2 text-xl font-extrabold text-[#9b753c]">{value}</p></div>)}</div></div><GoldCalculator liveGoldPrice={market?.gold18Price} /></div></div></section>

      <section className="relative overflow-hidden bg-[#f5f1e9] py-24 sm:py-32"><div className="waresh-container grid gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div><p className="text-xs font-bold tracking-[0.2em] text-[#9d7842]">FROM GILAN, FOR TOMORROW</p><h2 className="mt-5 text-4xl font-extrabold leading-[1.45] text-[#2b302a] sm:text-5xl">وارش را بیشتر بشناس.</h2><p className="mt-6 max-w-xl text-base leading-9 text-[#70756d]">«وارش» یعنی باران. داستان ریشه شمالی و نگاه ما به آینده را در صفحه درباره وارش بخوان.</p><a href="/about" className="mt-8 inline-flex rounded-full bg-[#263b31] px-6 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5">داستان وارش ←</a></div><div className="rounded-[3rem] bg-[#dce4d9] p-3 shadow-[0_25px_70px_rgba(55,65,53,0.12)]"><img src={forestImage} alt="طبیعت سبز گیلان" className="h-[360px] w-full rounded-[2.5rem] object-cover" /></div></div></section>

      <section className="bg-[#b28b4c] px-6 py-20 text-center text-white"><p className="text-xs font-bold tracking-[0.22em] text-white/75">WARESH GOLD</p><h2 className="mt-4 text-3xl font-extrabold sm:text-4xl">برای خرید یا مشاوره، با وارش در تماس باش.</h2><a href={TELEGRAM_BOT_URL} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-full bg-[#23372d] px-8 py-4 font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#182920]">شروع گفتگو در تلگرام</a></section>

      <footer className="bg-[#1f2d26] py-14 text-white"><div className="waresh-container flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><img src="/waresh-gold-logo-white.jpg" alt="وارش گلد" className="h-12 w-auto object-contain" /><p className="mt-4 text-sm text-white/55">دقیق، آرام، ایرانی.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-white/65"><a href="#products">محصولات</a><a href="#prices">قیمت امروز</a><a href="/tools">ابزارها</a><a href="/about">درباره وارش</a><a href={TELEGRAM_BOT_URL} target="_blank" rel="noopener noreferrer">تلگرام</a></div></div><div className="waresh-container mt-10 border-t border-white/10 pt-5 text-center text-xs text-white/40">© ۱۴۰۵ وارش گلد. تمامی حقوق محفوظ است.</div></footer>
    </main>
  );
}
